//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ExplorerXP.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_WINDOW_MANAGE               101
#define IDI_TABCTRLBAR                  101
#define ID_INDICATOR_OBJECTS            103
#define ID_INDICATOR_SIZE               104
#define ID_DRIVETREE                    105
#define IDD_SPLIT                       106
#define IDD_MERGE                       107
#define IDR_MAINFRAME                   128
#define IDR_EXPLORTYPE                  129
#define IDB_DBPROJECTS                  130
#define IDS_AUTOSIZETHIS                130
#define IDB_FILETYPES                   131
#define IDS_AUTOSIZEALL                 131
#define ID_FAVS                         132
#define IDS_SETTINGS                    133
#define IDS_CLOSETAB                    134
#define IDR_BUTTONBAR                   136
#define IDR_TABVIEW_MENU                138
#define IDR_RFOLDER                     142
#define IDR_EMPTY                       143
#define IDB_COLD                        145
#define IDB_GRAY                        147
#define IDR_RECYCLE                     148
#define IDR_MYCOMPUTER                  149
#define IDB_BITMAP1                     150
#define IDD_RENAME                      151
#define IDD_MULTIRENAME                 152
#define IDR_CASE                        153
#define IDR_CONVERT                     154
#define IDD_NEWFOLDER                   155
#define IDB_LOGO                        158
#define IDD_DIALOG1                     159
#define IDD_COPYMOVE                    159
#define IDI_ICON1                       160
#define IDD_SELECT                      160
#define IDD_CLEAN                       162
#define IDD_EDITFILTER                  163
#define IDD_EDITFILTERS                 164
#define IDI_ICON2                       165
#define IDD_OPTIONSSIMPLE               166
#define IDD_OPTIONS_SIMPLE              166
#define IDR_TABMENU                     168
#define IDR_GROUPS                      170
#define IDD_REN_COUNT                   171
#define IDD_REN_REPLACE                 172
#define IDD_REN_CASE                    173
#define IDD_REN_TRIM                    174
#define IDR_GROUP_ITEM                  175
#define IDB_HDRUP                       176
#define IDB_HDRDOWN                     177
#define IDD_KEYBOARD                    178
#define IDD_OPTIONS_KEYBOARD            178
#define IDD_SIZEOPTIONS                 179
#define IDD_OPTIONS_SIZE                179
#define IDD_REN_INSERT                  180
#define IDD_FINDMISSING                 181
#define IDD_OPTIONS_TAB                 183
#define IDB_HOOVERBMP                   184
#define IDD_SEARCH                      185
#define IDR_BINARY1                     187
#define IDD_FILECHARTS                  188
#define IDC_RECYCLE_FILES               201
#define IDD_OPTIONS                     202
#define IDC_ADD                         203
#define IDD_ADD_EDIT_PATTERN            203
#define IDC_EDIT                        204
#define IDC_DELETE                      205
#define IDC_PATTERN                     206
#define ID_INDICATOR_DRIVESINFO         207
#define ID_INDICATOR_OBJECTS_SELECTED   208
#define ID_INDICATOR_SIZE_SELECTERD     209
#define IDC_EDIT_INPUTFILE              1000
#define IDC_EDIT1                       1001
#define IDC_ORG_NAME                    1001
#define IDC_FIND                        1001
#define IDC_FOLDERNAME                  1001
#define IDC_EDIT_OUTPUTDIR              1001
#define IDC_NAME                        1001
#define IDC_WINDOWLIST_LIST             1002
#define IDC_BTN_SELINPUTFILE            1002
#define IDC_EDIT2                       1002
#define IDC_WINDOWLIST_ACTIVATE         1003
#define IDC_BTN_SELOUTPUTDIR            1003
#define IDC_EDIT3                       1003
#define IDC_FIND2                       1003
#define IDC_WHAT                        1003
#define IDC_WINDOWLIST_SAVE             1004
#define IDC_RDO_NFILES                  1004
#define IDC_EDIT4                       1004
#define IDC_WINDOWLIST_CLOSE            1005
#define IDC_RDO_FILESIZE                1005
#define IDC_ATSTARTLASTOPEND            1005
#define IDC_EDIT5                       1005
#define IDC_WINDOWLIST_CASCADE          1006
#define IDC_EDIT_NFILES                 1006
#define IDC_EDIT6                       1006
#define IDC_WINDOWLIST_TILEHORZ         1007
#define IDC_EDIT_FILESIZE               1007
#define IDC_WINDOWLIST_TILEVERT         1008
#define IDC_BTN_STARTSPLIT              1008
#define IDC_WINDOWLIST_MINIMIZE         1009
#define IDC_PROGRESS_SPLIT              1009
#define IDC_SP_STATIC                   1010
#define IDC_STATIC_ADDRESS              1011
#define IDC_BTN_STARTSPLIT2             1011
#define IDC_BTN_STARTMERGE              1012
#define IDC_ADDRESS                     1013
#define IDC_PROGRESS_MERGE              1013
#define IDC_NEW_NAME                    1014
#define IDC_ME_STATIC                   1014
#define IDC_BTN_SELFILES                1015
#define IDC_EDIT_OUTFILE                1016
#define IDC_STATIC_RENAME               1017
#define IDC_BTN_FILEUP                  1017
#define IDC_STATIC_TO                   1018
#define IDC_BTN_FILEDOWN                1018
#define IDC_STATIC_DOWN                 1019
#define IDC_LIST_FILES                  1019
#define IDC_RENAME                      1020
#define IDC_STATIC_REPLACE_SEP          1020
#define IDC_BTN_FILEDEL                 1020
#define IDC_TO                          1021
#define IDC_BTN_FILEADD                 1021
#define IDC_STATIC_REPLACE_SEP2         1021
#define IDC_STATIC_OUTPUT_SEP           1021
#define IDC_STATIC_FILTERS              1021
#define IDC_FILES                       1022
#define IDC_BTN_SELDIR                  1022
#define IDC_CASE                        1023
#define IDC_STATIC_REPLACE_SEP3         1023
#define IDC_STATIC_SEP                  1023
#define IDC_CONVERT                     1024
#define IDC_CASE2                       1024
#define IDC_REPLACE                     1025
#define IDC_CASE3                       1025
#define IDC_STATIC_FILES_SEP            1026
#define IDC_CASE4                       1026
#define IDC_STATIC_LAST_SEP             1027
#define IDC_CASE5                       1027
#define IDC_HARMONDALE                  1029
#define IDC_LOGOBMP                     1030
#define IDC_VERSION                     1031
#define IDC_TIME                        1032
#define IDC_TREE1                       1033
#define IDC_FOLDERS                     1033
#define IDC_HARMONDALE2                 1033
#define IDC_LIST1                       1034
#define IDC_LIST                        1034
#define IDC_LAST_SEP                    1035
#define IDC_HARMONDALE3                 1035
#define IDC_WILDCARDS                   1036
#define IDC_HARMONDALE4                 1036
#define IDC_COMBO1                      1038
#define IDC_MULTIPLAYER                 1038
#define IDC_PATTERNS                    1038
#define IDC_STATIC_INPUT_SEP            1039
#define IDC_STATIC_INPUT                1040
#define IDC_STATIC_OUTPUT               1041
#define IDC_OUTPUT_STATIC               1043
#define IDC_EDITFILTERS                 1044
#define IDC_ATSTARTNONE                 1045
#define IDC_ATSTARTMYCOMP               1046
#define IDC_ATSTARTDEFAULT              1047
#define IDC_VERTICAL                    1049
#define IDC_HORIZONTAL                  1050
#define IDC_CHECK2                      1051
#define IDC_HIDDENFILES                 1051
#define IDC_HIDDENFILES2                1052
#define IDC_NOEXECUTABLESICONS          1052
#define IDC_HINT                        1053
#define IDC_NEW_EXT                     1054
#define IDC_STATIC_EXT                  1055
#define IDC_ASSIGNSHORTCUT              1056
#define IDC_CHECK1                      1057
#define IDC_STATIC_CHILD                1058
#define IDC_CONVERT1                    1061
#define IDC_CONVERT3                    1063
#define IDC_RIGHT                       1063
#define IDC_CONVERT4                    1064
#define IDC_SPIN1                       1064
#define IDC_CONVERT5                    1065
#define IDC_SPIN2                       1065
#define IDC_SPIN3                       1066
#define IDC_FROMRIGH                    1067
#define IDC_SIZE1                       1068
#define IDC_SIZE2                       1069
#define IDC_SIZE3                       1070
#define IDC_SINGLEINSTANCE              1071
#define IDC_SINGLEINSTANCE2             1072
#define IDC_RADIO1                      1072
#define IDC_FOLDERMODE_AUTO             1072
#define IDC_RADIO2                      1073
#define IDC_FOLDERMODE_MAN              1073
#define IDC_FOLDERMODE_DELAYED          1074
#define IDC_REPLACEALL                  1074
#define IDC_STRIP                       1075
#define IDC_LIMIT                       1076
#define IDC_LIMITCHAR                   1077
#define IDC_BUTTON1                     1078
#define IDC_SCROLLBAR1                  1080
#define IDC_NEWHOTKEY                   1082
#define IDC_CURHOTKEY                   1083
#define IDC_COMMANDS                    1084
#define IDC_INUSE                       1085
#define IDC_CURLABEL                    1088
#define IDC_NEWLABEL                    1089
#define IDD_DIALOG_WINLIST              1090
#define IDC_LIST_WINDOWS                1091
#define ID_IMAGE_TOOLBAR_TGA            5002
#define ID_WINDOWS_FIRST                32001
#define ID_WINDOWS_2                    32002
#define ID_WINDOWS_3                    32003
#define ID_WINDOWS_4                    32004
#define ID_WINDOWS_5                    32005
#define ID_WINDOWS_6                    32006
#define ID_WINDOWS_7                    32007
#define ID_WINDOWS_8                    32008
#define ID_WINDOWS_9                    32009
#define ID_WINDOWS_10                   32010
#define ID_WINDOWS_11                   32011
#define ID_WINDOWS_12                   32012
#define ID_WINDOWS_13                   32013
#define ID_WINDOWS_14                   32014
#define ID_WINDOWS_15                   32015
#define ID_WINDOWS_16                   32016
#define ID_WINDOWS_17                   32017
#define ID_WINDOWS_18                   32018
#define ID_WINDOWS_19                   32019
#define ID_WINDOWS_LAST                 32020
#define ID_WINDOWS_MORE                 32020
#define ID_BACK                         32771
#define ID_VIEW_FULLSCREEN              32772
#define ID_FORWARD                      32773
#define ID_WINDOW_NEXT                  32774
#define ID_UP                           32775
#define ID_WINDOW_PREVIOUS              32776
#define ID_SEARCH                       32777
#define ID_FOLDERTREE                   32779
#define ID_WINDOW_SAVE_ALL              32780
#define ID_COPY                         32781
#define ID_DELETE                       32782
#define ID_UNDO                         32783
#define ID_MOVETO                       32784
#define IDS_WINDOW_MANAGE               32786
#define ID_VIEW_VIEWTAB                 32787
#define ID_DOWN                         32789
#define ID_PASTE                        32790
#define ID_EDIT_SELECTALL               32791
#define ID_EDIT_INVERTSELECTION         32792
#define ID_CUT                          32793
#define ID_POPUPFOLDER_OPEN             32794
#define ID_POPUPFOLDER_EXPLORE          32795
#define ID_POPUPFOLDER_COPY             32797
#define ID_POPUPFOLDER_PASTE            32798
#define ID_POPUPFOLDER_CREATESHORTCUT   32799
#define ID_POPUPFOLDER_DELETE           32800
#define ID_POPUPFOLDER_RENAME           32801
#define ID_POPUPFOLDER_PROPERTIES       32802
#define ID_POPUPFOLDER_SENDTO           32803
#define ID_MYCOMPUTER                   32804
#define ID_RECYCLEBIN                   32805
#define ID_BUTTON32806                  32806
#define ID_BUTTON32807                  32807
#define ID_BUTTON32808                  32808
#define ID_RECYCLE_EMPTY                32810
#define ID_RECYCLE_PROPERTIES           32811
#define ID_MYCOMPUTER_PROPERTIES        32812
#define ID_RECYCLE_RESTOREALL           32813
#define ID_RENAME                       32814
#define ID_SENTENCECASE                 32815
#define ID_LOWERCASE                    32816
#define ID_UPPERCASE                    32817
#define ID_TITLECASE                    32818
#define ID_TOGGLECASE                   32819
#define ID_CONVERT20TOSPACE             32820
#define ID_CONVERTUNDERSCORETOSPACE     32822
#define ID_CONVERTSPACETOUNDERSCORE     32823
#define ID_NEWFOLDER                    32824
#define ID_COMMANDS_DELETE              32825
#define ID_SELECTION_REMOVE             32826
#define ID_SELECTION_WILDCARDDESELECT   32827
#define ID_COMMANDS_MOVETO              32828
#define ID_COMMANDS_COPYTO              32829
#define ID_REFRESH                      32831
#define ID_VIEW_ADDRESSBAR              32832
#define ID_COPYTO                       32833
#define ID_MYDOCUMENTS                  32834
#define ID_COMMANDS_SPLIT               32835
#define ID_COMMANDS_MERGE               32836
#define ID_COMMANDS_CLEAN               32837
#define ID_COPYCLIPBOARD                32839
#define ID_HELP_HELP                    32840
#define ID_VIEW_TABSONTOP               32841
#define ID_VIEW_TABSONBOTTOM            32842
#define ID_FILE_OPTIONS                 32843
#define ID_SAVEDEFAULT                  32845
#define ID_MOVETOADDRESSBAR             32846
#define ID_ADDRESSSHOWDROPDOWN          32849
#define ID_VIEW_ARANAGEFILESBY          32851
#define ID_ARANAGEFILESBY_NAME          32852
#define ID_ARANAGEFILESBY_SIZE          32853
#define ID_ARANAGEFILESBY_SIZEONDISK    32854
#define ID_ARANAGEFILESBY_TYPE          32855
#define ID_ARANAGEFILESBY_MODIFED       32856
#define ID_ACCELERATOR32857             32857
#define ID_PROPERTIES                   32857
#define ID_VIEW_CUSTOMIZETOOLBAR        32859
#define ID_DESKTOP                      32860
#define ID_FOLDERS_RESETALLFOLDERS      32862
#define ID_FOLDERS_MAKEASTHISFOLDER     32863
#define ID_EMPTY                        32864
#define ID_EMPTY_WILDCARDSELECT         32865
#define ID_SELECTION_WILDCARDSELECT     32866
#define ID_DOWN32867                    32867
#define ID_Menu                         32868
#define ID_XX_CLOSEOTHERTABS            32869
#define ID_WINDOW_CLOSE_ALL             32870
#define ID_GROUPS_ADDANEWGROUP          32871
#define ID_GROUPS_SAVEOPENFOLDERSASGROUP 32872
#define ID__XXX                         32873
#define ID_GROUPS_ADDTO                 32878
#define ID_NEWGROUP                     32880
#define ID_DELETEGROUP                  32881
#define ID_CLOSEALLOPENGROUP            32883
#define ID_RENAMEGROUP                  32884
#define ID_OPENGROUP                    32885
#define ID_CONVERTPOINTTOSPACE          32887
#define ID_OPENGROUPITEM                32888
#define ID_EXPLOREGROUPITEM             32889
#define ID_DELETEGROUPITEM              32890
#define ID_HELP_EXPLORERXPHOMEPAGE      32891
#define ID_HELP_COMMUNITY               32892
#define ID_EMPTY_NEW                    32893
#define ID_NEW_XXX                      32895
#define ID_DELETEPERMENTLY              32901
#define ID_SELECTION_SELECTSIMILAR      32908
#define ID_COMMANDS_CMD                 32911
#define ID_EDIT_COPYFOLDERPATHTOCLIPBOARD 32914
#define ID_EDIT_COPYTOPARENT            32915
#define ID_EDIT_COPYTOSUB               32916
#define ID_EDIT_COPYFILENAMETOCLIPBOARD 32917
#define ID_EDIT_COPYFULLPATHNAMESASTEXT 32918
#define ID_EDIT_MOVETOTABS              32927
#define ID_EDIT_MOVETOGROUPS            32928
#define ID_COMMANDS_FINDMISSING         32931
#define ID_GO_UP                        32938
#define ID_GO_FORWARD                   32939
#define ID_GO_BACKWARD                  32940
#define ID_GO_MYCOMPUTER                32941
#define ID_GO_DESKTOP                   32942
#define ID_GO_MYDOCUMENTS               32943
#define ID_GO_RECYCLEBIN                32944
#define ID_ADDFOLDERTOGROUP             32946
#define ID_COMMANDS_FINDDUPLICATES      32947
#define ID_RECYCLEBIN_FULL              32948
#define ID_COMMANDS_SHOWCHARTS          32949
#define ID_WINDOWS_CASCADE              32950
#define ID_WINDOWS_TILE_HORZ            32951
#define ID_WINDOWS_ARRANGE              32952
#define ID_WINDOWS_TILE_VERT            32953
#define ID_WINDOWS_NEXT                 32954
#define ID_WINDOWS_PREVIOUS             32955
#define ID_WINDOWS_CLOSE_ALL            32956
#define ID_TEMPFOLDER                   32957

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        193
#define _APS_NEXT_COMMAND_VALUE         32958
#define _APS_NEXT_CONTROL_VALUE         1081
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
